### ISSUE TITLE
Setup true checkpointing

### ISSUE THREAD

**Issue by Vectorrent** [0-5788719150923125/vtx#8]
https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html

**Comment by Vectorrent** [comment]
Simple checkpoint saving/loading has been implemented via two training arguments:
```
src:
  training:
    checkpoint: True
    resume: True
```
